spring:
  application:
    name: easy-spring-auth
  view-component:
    local-development: true
    jte-template-directories: lab-2/src/main/java
#gg:
 # jte:
  #  developmentMode: true
   # templateLocation: lab-2/src/main/jte
